sudo: required
services: 
  - docker
before-install:
  - docker build -t elraphty/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true elraphty/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "my-react"
  env: "Myreact-env"
  bucket-name: "elasticbeanstalk-us-east-2-013582956519"
  bucket-path: "my-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"