language: generic
sudo: required
services: 
  - docker
before-install:
  - docker build -t elraphty/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true elraphty/docker-react npm run test